version: "2"
services:
  chirpstack-api-go:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd go && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd swagger && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-js:
    environment:
      - VERSION=3.12.4
    build:
      context: .
      dockerfile: Dockerfile-js
    command: bash -c "cd js && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-rust:
    environment:
      - VERSION=3.12.4
    build:
      context: .
      dockerfile: Dockerfile-rust
    command: bash -c "cd rust && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-python:
    environment:
      - VERSION=3.12.4
    build:
      context: .
      dockerfile: Dockerfile-python
    command: bash -c "cd python && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-java:
    user: ${CURRENT_UID}
    environment:
      - VERSION=3.12.4
      - MAVEN_CONFIG=/var/maven/.m2
    build:
      context: .
      dockerfile: Dockerfile-java
    command: bash -c "cd java && make all"
    volumes:
      - ./:/chirpstack-api
      - ${CURRENT_HOME}/.m2:/var/maven/.m2
