version: "2"
services:
  chirpstack-api-go:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd go && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd swagger && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-js:
    build:
      context: .
      dockerfile: Dockerfile-js
    command: bash -c "cd js && make all"
    volumes:
      - ./:/chirpstack-api
  chirpstack-api-rust:
    environment:
      - VERSION=3.0.3
    build:
      context: .
      dockerfile: Dockerfile-rust
    command: bash -c "cd rust && make all"
    volumes:
      - ./:/chirpstack-api
