[package]
name = "chirpstack_api"
description = "ChirpStack Protobuf / gRPC API definitions."
version = "3.1.1"
authors = ["Orne Brocaar <info@brocaar.com>"]
license = "MIT"
homepage = "https://www.chirpstack.io"
repository = "https://github.com/brocaar/chirpstack-api"
edition = "2018"

[features]
default = ["grpc_support"]
grpc_support = ["tonic/transport", "tokio"]

[dependencies]
prost = "0.6"
prost-types = "0.6.1"

tonic = { version = "0.1", features = ["codegen"], default-features = false }
tokio = { version = "0.2", features = ["macros"], optional = true }

[build-dependencies]
tonic-build = "0.1.0"
