[package]
name = "chirpstack_api"
description = "ChirpStack Protobuf / gRPC API definitions."
version = "3.6.6"
authors = ["Orne Brocaar <info@brocaar.com>"]
license = "MIT"
homepage = "https://www.chirpstack.io"
repository = "https://github.com/brocaar/chirpstack-api"
edition = "2018"

[features]
default = ["grpc_support", "rustfmt"]
grpc_support = ["tonic/transport", "tonic-build/transport", "tokio"]
rustfmt = ["tonic-build/rustfmt"]

[dependencies]
prost = "0.6"
prost-types = "0.6.1"

tonic = { version = "0.1", features = ["codegen"], default-features = false }
tokio = { version = "0.2", features = ["macros"], optional = true }

[build-dependencies]
tonic-build = { version = "0.1", default-features = false }
